# Generated by Django 2.0.2 on 2018-03-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(max_length=1000, upload_to=''),
        ),
    ]
