# Generated by Django 2.0.2 on 2018-03-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0002_auto_20180323_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
